# Generated by Django 5.0.1 on 2024-01-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mobile',
            field=models.IntegerField(default=123456789),
            preserve_default=False,
        ),
    ]
